Directional commands
MissouriMRR/Offboard-Commands pull request #6
Opened 2023-10-11 00:35 UTC by DJDMVP

Basic Directional commands for reference for object avoidance. Uses velocity to move a certain distance based on drone body. There are a couple movement commands including in each direction, in a diagonal, and rotating.

2023-10-18 00:49 UTC, cjhr95 requested changes
Just some small stuff on variable naming

2023-10-18 00:49 UTC, cjhr95 commented on Commands/forward.py
> +    move_time: float = distance / 20
Change the denominator to ms_speed

2023-10-18 00:49 UTC, cjhr95 commented on Commands/left.py
> +    move_time: float = distance / 20
Change the denominator to ms_speed

2023-10-18 00:49 UTC, cjhr95 commented on Commands/movement.py
> +    drone: System, rightdistance: float, forwarddistance: float, updistance: float
Add some underscores to these parameters to adhere to snake_case

2023-10-18 00:49 UTC, cjhr95 commented on Commands/movement.py
> +        distance in meters wanted to go up
Same here, change parameter names to match the function definition

2023-10-18 00:49 UTC, cjhr95 commented on Commands/test.py
> +    await drone.action.set_maximum_speed(25)
Have these parameters be set to constants for readability & easy edits

2023-10-18 00:49 UTC, cjhr95 commented on Commands/test.py
> +    """
Remove the large comment block

2023-10-20 00:31 UTC, cjhr95 requested changes
Some very small, itty-bitty formatting stuff

2023-10-20 00:31 UTC, cjhr95 commented on Commands/test.py
> +# from downward import downward
Remove the unused imports

2023-10-20 00:31 UTC, cjhr95 commented on Commands/test.py
> +
```suggestion
```

2023-10-20 00:57 UTC, RexBerry commented
Forgot the emoticon in the commit message:
👁️👄👁️

2023-10-20 00:59 UTC, cjhr95 approved these changes
Yeah it's alright or whatever

2023-10-20 00:59 UTC, merged